# Generated by Django 3.0.5 on 2020-04-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200425_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comprut',
            field=models.BooleanField(null=True),
        ),
    ]
