# Generated by Django 3.0.5 on 2020-04-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_user_comprut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comprut',
            field=models.BooleanField(),
        ),
    ]
